### PR TITLE
- Added the ability to save files to desk- Removed warnings generated by the plugin

### PR DESCRIPTION
**Pull request by shbli**

### CODE REVIEW

**Comment by shbli** [comment]
This adds a feature to save the logs to device, useful to export the logs from test user devices and send them back to the dev team

**Comment by aliessmael** [comment]
Thanks for this improvement, I will merge it once I have time to test it properly.

**Comment by GabLeRoux** [comment]
The diff of this is kind of weird and hard to review. The feature seems like a good idea tho. Commit message should be reworked too.

**Comment by aliessmael** [comment]
done

**Pull request closed without merging**
